server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: confi-server
          uri: https://github.com/sIttayGarcia/microservicios-tutorial
          search-paths: config-data
  application:
    name: confi-service